version: "3"
services:
  server:
    image: node:17-alpine3.12
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app/server
    command: sh -c "cd /app/server && npm install && npm run ${MODE}"
