site_name: Server Area
site_url: http://localhost:3000
nav:
  - Home: index.md
  - 'Auth':
      - CreateUser: auth/createUser.md
      - DeleteUser: auth/deleteUser.md
      - SignUser: auth/signUser.md
      - SignUserProvider: auth/signUserProvider.md
  - 'Services':
      - GetAllServices: services/getAllServices.md
      - GetService: services/getService.md
theme:
  name: material
