site_name: Server Area
site_url: http://localhost:3000
nav:
  - Home: index.md
  - 'Auth':
      - Create User: auth/createUser.md
      - Delete User: auth/deleteUser.md
      - Sign User: auth/signUser.md
      - Sign User Provider: auth/signUserProvider.md
  - 'Services':
      - Get All Services: services/getAllServices.md
      - Get Service: services/getService.md
  - 'Actions':
      - Create Action Reaction: actions/createActionReaction.md
      - Delete Action Reaction: actions/deleteActionReaction.md
      - GitHub Action Reaction: actions/Github.md
      - Weather Action Reaction: actions/Weather.md
theme:
  name: material
